# Tymczasowa konfiguracja wygenerowana przez launcher
# Oryginalny config.py został zachowany jako config_backup.py

ENABLE_OBSTACLES = True
ENABLE_ADVANCED_NAVIGATION = True
ENABLE_PHEROMONE_GRADIENT = True
ENABLE_ANT_MEMORY = True
ENABLE_DYNAMIC_SPEED = True
ENABLE_ANT_SPECIALIZATION = True
ANT_BASE_SPEED = 1
PHEROMONE_DECAY_RATE = 0.995
INITIAL_ANT_COUNT = 30
FPS = 30
SCOUT_SPEED_MULTIPLIER = 1.2
COLLECTOR_SPEED_MULTIPLIER = 0.6
GUARD_SPEED_MULTIPLIER = 0.8
